Use single line for multiple files
conan-io/hooks pull request #233
Opened 2020-09-08 13:33 UTC by uilianries

The hooks KB-H016, KB-H017, KB-H018, KB-H019, KB-H020 and KB-H021 use "\n" to show each file found by the hook. It works for logs, but for Github comments don't.

The idea here is printing all files at same line, but using ";" as separator. 

fixes https://github.com/conan-io/hooks/issues/230

2020-09-08 13:34 UTC, danimtb approved these changes

2020-09-08 14:15 UTC, jgsogo approved these changes

2020-09-08 14:17 UTC, jgsogo commented
Yes, I think it should be a good practice to report only one line per hook. Anyway we should probably revisit the output reported to Github when hooks fails.

btw, I'm adding _close https://github.com/conan-io/conan-center-index/issues/2856_ to the main comment

2020-10-05 07:37 UTC, danimtb commented
@uilianries the CI is red, can you check it please?

2020-10-06 07:07 UTC, danimtb commented
still failing

2020-10-06 13:15 UTC, uilianries commented
Yes, indeed I can't reproduce, I'll try different containers.

As is failed for Conan dev branch, I thought it was related to a specific commit available on develop branch, as it works for me, but I can see that's not the case.

2020-10-06 14:35 UTC, jgsogo requested changes
Error is related to file ordering:


```
ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] Found files: ./XXXConfig.cmake; ./FindXXX.cmake
ERROR: [CMAKE-MODULES-CONFIG-FILES (KB-H016)] Found files: ./FindXXX.cmake; ./XXXConfig.cmake
```

Call `sort` before returning files from `_get_files_following_patterns`, OS doesn't guarantee that order.

2020-10-07 17:25 UTC, jgsogo approved these changes
Hope it works now!

2020-10-07 18:59 UTC, uilianries commented
@jgsogo it's working! Gracias!

2020-10-08 10:06 UTC, danimtb approved these changes

2020-10-08 10:06 UTC, merged