KB-H053: allow custom generators
conan-io/hooks pull request #245
Opened 2020-10-19 07:35 UTC by ericLemanissier

conans.model.Generator is explicitly documented in https://docs.conan.io/en/latest/howtos/custom_generators.html

see https://github.com/conan-io/conan-center-index/pull/1759#issuecomment-711129395

2020-10-19 18:48 UTC, uilianries requested changes

2020-10-19 18:48 UTC, uilianries commented on hooks/conan-center.py
> +
```suggestion
        if conanfile.name in ["qt"]:
            out.info("'{}' is part of the allowlist.".format(conanfile.name))
            return

        def _is_private_import(line):
```

2020-10-28 17:25 UTC, ericLemanissier commented on hooks/conan-center.py
>              allowed_list = ["tools", "errors"]
```suggestion            
            allowed_list = ["tools", "errors", "model.Generator"]
```
@uilianries what do you think of this one ?

2020-10-30 18:28 UTC, uilianries commented on hooks/conan-center.py
>              allowed_list = ["tools", "errors"]
sounds better!

2020-10-31 02:13 UTC, uilianries approved these changes

2020-11-05 08:08 UTC, ericLemanissier commented
this is blocking https://github.com/conan-io/conan-center-index/pull/1759

2020-11-24 11:09 UTC, ericLemanissier commented
sorry, for the noise, but is there something blocking on this one ? @danimtb @jgsogo

2020-11-24 11:31 UTC, jgsogo approved these changes

2020-11-24 11:32 UTC, merged