Do not accept two ways for requirements
conan-io/hooks pull request #261
Opened 2020-12-23 18:42 UTC by uilianries

closes https://github.com/conan-io/hooks/issues/254

/cc @SpaceIm @mathbunnyru

2020-12-23 18:59 UTC, SSE4 commented on hooks/conan-center.py
> +            out.error("Both 'requires' attribute and 'requirements' method should not be "
hm, to clarify, why not? what happens if you declare both, which one takes priority?

2020-12-23 19:04 UTC, uilianries commented on hooks/conan-center.py
> +            out.error("Both 'requires' attribute and 'requirements' method should not be "
I guess self.requires comes first: https://github.com/conan-io/conan/blob/develop/conans/model/conan_file.py#L47

However, I see no motivation to use both, otherwise we would need to check places instead of one.

2020-12-23 19:08 UTC, mathbunnyru requested changes
LGTM, but I think having parentheses makes it a bit more clear.

2020-12-23 19:08 UTC, mathbunnyru commented on hooks/conan-center.py
> +            out.error("Both 'requires' attribute and 'requirements' method should not be "
```suggestion
            out.error("Both 'requires' attribute and 'requirements()' method should not be "
```

2020-12-23 19:08 UTC, mathbunnyru commented on tests/test_hooks/conan-center/test_conan-center.py
> +        self.assertIn("[SINGLE REQUIRES (KB-H054)] Both 'requires' attribute and 'requirements' "
```suggestion
        self.assertIn("[SINGLE REQUIRES (KB-H054)] Both 'requires' attribute and 'requirements()' "
```

2020-12-23 19:10 UTC, mathbunnyru commented
Do we want to check build_requires as well?

2020-12-23 20:11 UTC, mathbunnyru approved these changes
Good job 👍

2020-12-24 14:54 UTC, SSE4 approved these changes

2020-12-24 15:07 UTC, jgsogo commented
Please, do not merge it yet... if some recipes are going to fail (https://github.com/conan-io/conan-center-index/issues/2232). First, we would like to fix internal jobs (jobs building missing configurations behind the scenes) so they don't fail due to hook-validation, then we can introduce as many hooks as we want that fail in PRs.

Let's wait after 🎅 

Thanks!

2021-02-18 12:00 UTC, mathbunnyru commented
@jgsogo is it already possible to merge this PR?

2021-02-18 15:38 UTC, danimtb approved these changes

2021-03-02 09:11 UTC, jgsogo approved these changes
Please, @uilianries , fix conflicts

2021-03-02 11:52 UTC, uilianries commented
@jgsogo Done, I needed to update hook's id too.

2021-03-02 12:28 UTC, mathbunnyru approved these changes

2021-03-02 12:58 UTC, jgsogo approved these changes
I hope it doesn't break more than needed 😅

2021-03-02 12:58 UTC, merged