Add hook to verify class name
conan-io/hooks pull request #264
Opened 2021-01-07 14:53 UTC by theirix

A few recipes have names like `LibnameConan`.
Preassigned id KB-H054.

2021-01-11 08:28 UTC, danimtb approved these changes

2021-02-08 14:30 UTC, uilianries reviewed
The message could be more helpful.

2021-02-08 14:30 UTC, uilianries commented on hooks/conan-center.py
> +            out.error("Class name {} is not allowed".format(class_name))
```suggestion
            out.error("Class name '{}' is not allowed. Use 'Conan{}' instead.".format(class_name, conanfile.name))
```

2021-02-08 14:30 UTC, uilianries commented on tests/test_hooks/conan-center/test_conan-center.py
> +        self.assertIn("ERROR: [CLASS NAME (KB-H054)] Class name LibnameConan is not allowed", output)
```suggestion
        self.assertIn("ERROR: [CLASS NAME (KB-H054)] Class name 'LibnameConan' is not allowed. Use 'Conanname' instead.", output)
```

2021-02-18 11:58 UTC, mathbunnyru requested changes

2021-02-18 11:58 UTC, mathbunnyru commented on hooks/conan-center.py
> +            out.error("Class name '{}' is not allowed. Use 'Conan{}' instead.".format(class_name, conanfile.name))
```suggestion
            out.error("Class name '{}' is not allowed. For example, use '{}Conan' instead.".format(class_name, conanfile.name))
```

2021-02-18 11:58 UTC, mathbunnyru commented on hooks/conan-center.py
> +            out.error("Class name '{}' is not allowed. Use 'Conan{}' instead.".format(class_name, conanfile.name))
`{}Conan` is more widely used, I think.

2021-02-18 16:53 UTC, uilianries approved these changes

2021-02-18 17:05 UTC, mathbunnyru requested changes

2021-02-18 17:05 UTC, mathbunnyru commented on tests/test_hooks/conan-center/test_conan-center.py
> +        self.assertIn("ERROR: [CLASS NAME (KB-H054)] Class name 'LibnameConan' is not allowed. Use 'Conanname' instead.", output)
```suggestion
        self.assertIn("ERROR: [CLASS NAME (KB-H054)] Class name 'LibnameConan' is not allowed. For example, use 'nameConan' instead.", output)
```

2021-02-18 17:05 UTC, mathbunnyru commented on tests/test_hooks/conan-center/test_conan-center.py
> +        self.assertIn("ERROR: [CLASS NAME (KB-H054)] Class name 'LibnameConan' is not allowed. Use 'Conanname' instead.", output)
Sorry, I forgot to update the test.

2021-02-19 09:45 UTC, danimtb approved these changes

2021-06-15 16:54 UTC, uilianries commented
Hello @theirix I see there is a conflict here. Could you please solve it, so we can merge you PR.

2021-06-15 18:07 UTC, theirix commented
> Hello @theirix I see there is a conflict here. Could you please solve it, so we can merge you PR.

Sure! Rebased on master.

2021-06-15 19:48 UTC, uilianries commented
Thank you!

2021-06-15 19:48 UTC, uilianries submitted a review, later dismissed

2021-06-17 10:52 UTC, danimtb requested changes

2021-06-17 10:52 UTC, danimtb commented on hooks/conan-center.py
> +        if class_name in ("LibnameConan", "ConanRecipe", "ConanFileDefault"):
Let's allow `ConanRecipe` just in case we want to implement something around a common class name in the future of Conan. I think that should be a good common class name.
```suggestion
        if class_name in ("LibnameConan", "ConanFileDefault"):
```

2021-06-17 10:54 UTC, danimtb commented
I have run this hook check over the current recipes in CCI and we can expect the following references (around 15 recipes) to fail after this PR is merged:

```
FAIL: conan export recipes/abseil/all abseil/20200205@
FAIL: conan export recipes/abseil/all abseil/20200225.2@
FAIL: conan export recipes/abseil/all abseil/20200225.3@
FAIL: conan export recipes/abseil/all abseil/20200923@
FAIL: conan export recipes/abseil/all abseil/20200923.1@
FAIL: conan export recipes/abseil/all abseil/20200923.2@
FAIL: conan export recipes/abseil/all abseil/20200923.3@
FAIL: conan export recipes/abseil/all abseil/20210324.0@
FAIL: conan export recipes/abseil/all abseil/20210324.1@
FAIL: conan export recipes/abseil/all abseil/20210324.2@
FAIL: conan export recipes/aruco/3.x.x aruco/3.1.12@
FAIL: conan export recipes/atk/all atk/2.36.0@
FAIL: conan export recipes/catch2/2.x.x catch2/2.9.2@
FAIL: conan export recipes/catch2/2.x.x catch2/2.11.0@
FAIL: conan export recipes/catch2/2.x.x catch2/2.11.1@
FAIL: conan export recipes/catch2/2.x.x catch2/2.11.3@
FAIL: conan export recipes/catch2/2.x.x catch2/2.12.0@
FAIL: conan export recipes/catch2/2.x.x catch2/2.12.1@
FAIL: conan export recipes/catch2/2.x.x catch2/2.12.2@
FAIL: conan export recipes/catch2/2.x.x catch2/2.12.3@
FAIL: conan export recipes/catch2/2.x.x catch2/2.12.4@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.0@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.1@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.2@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.3@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.4@
FAIL: conan export recipes/catch2/2.x.x catch2/2.13.6@
FAIL: conan export recipes/gdk-pixbuf/all gdk-pixbuf/2.42.0@
FAIL: conan export recipes/gdk-pixbuf/all gdk-pixbuf/2.42.2@
FAIL: conan export recipes/gdk-pixbuf/all gdk-pixbuf/2.42.4@
FAIL: conan export recipes/graphene/all graphene/1.10.2@
FAIL: conan export recipes/graphene/all graphene/1.10.4@
FAIL: conan export recipes/graphene/all graphene/1.10.6@
FAIL: conan export recipes/gsoap/all gsoap/2.8.103@
FAIL: conan export recipes/gsoap/all gsoap/2.8.104@
FAIL: conan export recipes/gsoap/all gsoap/2.8.105@
FAIL: conan export recipes/gsoap/all gsoap/2.8.106@
FAIL: conan export recipes/libsndfile/1.0.28 libsndfile/1.0.28@
FAIL: conan export recipes/libsrtp/all libsrtp/2.3.0@
FAIL: conan export recipes/pfr/all pfr/1.0.4@
FAIL: conan export recipes/qpoases/all qpoases/3.2.1@
FAIL: conan export recipes/roaring/all roaring/0.2.66@
FAIL: conan export recipes/robin-hood-hashing/all robin-hood-hashing/3.7.0@
FAIL: conan export recipes/robin-hood-hashing/all robin-hood-hashing/3.8.0@
FAIL: conan export recipes/robin-hood-hashing/all robin-hood-hashing/3.9.1@
FAIL: conan export recipes/robin-hood-hashing/all robin-hood-hashing/3.11.1@
FAIL: conan export recipes/serial/all serial/1.2.1@
FAIL: conan export recipes/yas/7.x.x yas/7.0.4@
FAIL: conan export recipes/yas/7.x.x yas/7.0.5@
```

2021-06-17 18:52 UTC, theirix commented on hooks/conan-center.py
> +        if class_name in ("LibnameConan", "ConanRecipe", "ConanFileDefault"):
Okay, it would be nice to have `ConanRecipe` as a transitional name, merging.

Regarding the list of recipes - the hook is pre-export so it will affect only changed or rebuilt recipes.

2021-06-19 20:37 UTC, prince-chrismc commented on hooks/conan-center.py
> +             "KB-H057": "CLASS NAME",
57 is #294 ?

2021-06-19 20:40 UTC, prince-chrismc submitted a review, later dismissed

2021-06-19 20:40 UTC, prince-chrismc commented
Theres more merge conflicts

2021-06-20 05:46 UTC, theirix commented on hooks/conan-center.py
> +             "KB-H057": "CLASS NAME",
Yes. Updated this to 59 to allow merging other open PRs

2021-06-20 13:40 UTC, prince-chrismc approved these changes

2021-06-22 10:23 UTC, danimtb commented
I guess it is not very important as the check is already passing in most of the recipes in conan-center-index, but I'd like to get more feedback from other contributors like @SpaceIm and @madebr about this

2021-06-22 12:09 UTC, madebr commented on hooks/conan-center.py
> +            out.error("Class name '{}' is not allowed. For example, use '{}Conan' instead.".format(class_name, conanfile.name))
Your suggestion might be invalid: e.g. `android-ndkConan`.
How about the following?
```suggestion
            camel_name = "".join(s.title() for s in re.split("[^a-zA-Z]", conanfile.name))
            out.error("Class name '{}' is not allowed. For example, use '{}Conan' instead.".format(class_name, camel_name))
```

(make sure `re` is imported)

2021-06-26 12:02 UTC, madebr commented on tests/test_hooks/conan-center/test_conan-center.py
> +            {}
You don't use `.format`, so this actually creates a python set object.
```suggestion
```

2021-06-26 12:02 UTC, madebr commented on tests/test_hooks/conan-center/test_conan-center.py
> +            {}
same
```suggestion
```

2021-06-26 16:10 UTC, theirix commented on tests/test_hooks/conan-center/test_conan-center.py
> +            {}
Hmm, copied it from `test_non_ascii_characters`

2021-06-26 16:16 UTC, madebr submitted a review, later dismissed

2021-06-26 16:46 UTC, prince-chrismc submitted a review, later dismissed

2021-06-28 13:19 UTC, uilianries approved these changes
I would change it to warning only, because is more a style check.

2021-06-28 13:24 UTC, madebr commented
> I would change it to warning only, because is more a style check.

Same, let's not be too harsh on new contributors.

2021-06-28 14:01 UTC, uilianries commented
Before merging this PR, some recipe should be updated:

```shell
$ grep  -E 'LibnameConan|ConanFileDefault' -r 
recipes/atk/all/conanfile.py:class LibnameConan(ConanFile):
recipes/gsoap/all/conanfile.py:class ConanFileDefault(ConanFile):
recipes/gdk-pixbuf/all/conanfile.py:class LibnameConan(ConanFile):
recipes/graphene/all/conanfile.py:class LibnameConan(ConanFile):
recipes/aruco/3.x.x/conanfile.py:class LibnameConan(ConanFile):
recipes/yas/7.x.x/conanfile.py:class LibnameConan(ConanFile):
recipes/libsndfile/1.0.28/conanfile.py:class LibnameConan(ConanFile):
```

2021-06-28 15:10 UTC, theirix commented
> I would change it to warning only, because is more a style check.

It is a good idea, and it would not break listed recipes. Did not thought about this check being a warning...

2021-06-28 15:17 UTC, uilianries approved these changes

2021-06-28 15:18 UTC, uilianries commented
> Before merging this PR, some recipes should be updated:
> 
> ```shell
> $ grep  -E 'LibnameConan|ConanFileDefault' -r 
> recipes/atk/all/conanfile.py:class LibnameConan(ConanFile):
> recipes/gsoap/all/conanfile.py:class ConanFileDefault(ConanFile):
> recipes/gdk-pixbuf/all/conanfile.py:class LibnameConan(ConanFile):
> recipes/graphene/all/conanfile.py:class LibnameConan(ConanFile):
> recipes/aruco/3.x.x/conanfile.py:class LibnameConan(ConanFile):
> recipes/yas/7.x.x/conanfile.py:class LibnameConan(ConanFile):
> recipes/libsndfile/1.0.28/conanfile.py:class LibnameConan(ConanFile):
> ```

As this hook is a Warning now, we don't need to wait. We can update when bumping a version for instance.

2021-06-28 15:20 UTC, theirix commented
> > Before merging this PR, some recipes should be updated:
> > ```shell
> > $ grep  -E 'LibnameConan|ConanFileDefault' -r 
> > recipes/atk/all/conanfile.py:class LibnameConan(ConanFile):
> > recipes/gsoap/all/conanfile.py:class ConanFileDefault(ConanFile):
> > recipes/gdk-pixbuf/all/conanfile.py:class LibnameConan(ConanFile):
> > recipes/graphene/all/conanfile.py:class LibnameConan(ConanFile):
> > recipes/aruco/3.x.x/conanfile.py:class LibnameConan(ConanFile):
> > recipes/yas/7.x.x/conanfile.py:class LibnameConan(ConanFile):
> > recipes/libsndfile/1.0.28/conanfile.py:class LibnameConan(ConanFile):
> > ```
> 
> As this hook is a Warning now, we don't need to wait. We can update when bumping a version for instance.

That's good! I filed only atk update for now and then decided that it can wait for modernization or bumps :)

2021-06-28 17:19 UTC, madebr approved these changes

2021-06-28 17:43 UTC, danimtb approved these changes

2021-06-28 17:44 UTC, merged