#312 Validate minimum Cmake version when cxx_std_11 is declared
conan-io/hooks pull request #328
Opened 2021-08-05 15:41 UTC by uilianries

CMake CXX features for cxx_std are available since CMake 3.8

https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html

/cc @prince-chrismc
closes #312

2021-08-06 00:05 UTC, prince-chrismc reviewed
`cxx_std_20` was added in in 3.12 https://cmake.org/cmake/help/v3.12/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html

but that's extra

2021-08-06 00:05 UTC, prince-chrismc commented on hooks/conan-center.py
> +                match = re.search(r"cmake_minimum_required\(version [\"']?(\w\.\w+)", cmake_content.lower())
I would have expected digits not words 🤔 

```suggestion
            cxx_std = re.search(r"cxx_std_\d+", cmake_content)
            if cxx_std:
                match = re.search(r"cmake_minimum_required\(version [\"']?(\d\.\d+)", cmake_content.lower())
```

2021-08-06 01:58 UTC, uilianries commented on hooks/conan-center.py
> +                match = re.search(r"cmake_minimum_required\(version [\"']?(\w\.\w+)", cmake_content.lower())
Word is equivalent to [A-Za-z0-9_], but yeah, digits should fit better.

2021-08-06 02:00 UTC, prince-chrismc approved these changes

2021-08-06 02:26 UTC, Croydon commented on hooks/conan-center.py
> +             "KB-H063": "CMAKE REQUIRED VERSION - CXX_STD",
Please no more extra hooks for the minimum CMake version required. I think we should combine them all into a single one. Either now or with Conan 2.0 when we increase the CMake version higher than all those hooks require, but probably sooner is better

2021-08-06 07:36 UTC, SSE4 commented
I am personally tentative if we want to maintain that... perhaps, no?
this would eventually evolve into code validating all the cmake statements, variables, functions, etc. match the minimum required version. I don't think it's our (hook's or CCI's) job to validate that.
the list will keep growing for each new CMake release.
if library requires some CMake release, it just won't build without it - so there is no point to additionally validate it ourselves?
in general, this approach is very questionable for me, I don't see a huge benefit, only snowball of slowly adding more and more CMake variables to check.

2021-08-06 07:47 UTC, jgsogo commented
I wonder why CMake doesn't raise an error for this kind of thing. I would like CMake to fail if something is not known to that version... Does anyone know any reason for it? I really don't like adding checks that should be done by someone else.

As a proposal, and (I think) aligned with other's comments: let's keep `conan-center` hook for things that are important/required to ConanCenter... and maybe we can start a hook called `cmake-xxxx` that performs all kinds of checks related to CMake. We can activate both hooks in ConanCenter, or maybe we just activate `cmake-xxx` when running this job https://github.com/conan-io/conan-center-index/issues/2232 to make less noise in pull-requests.

2021-08-06 14:31 UTC, uilianries commented
It would be great an API support from Cmake or even a better internal checker. Let's shelve the PR

2021-08-09 06:23 UTC, SSE4 requested changes
right now, I don't think it's a job of conan center hook to validate CMake functions used by the library or recipe.

2021-09-10 06:12 UTC, SSE4 commented
that's an obscure nature of CMake, and it's by design, it will never complain about variables it doesn't know.
if `CMAKE_CXX_KNOWN_FEATURES` is not known to older CMake release, it will be just assumed an empty value, and CMake will run normally to some degree.
that's how they decided about syntax from the beginning, and it's different from C++ any other languages. perhaps, it allows to write code faster without thinking too much about details like initializing everything.
e.g:
```
message(STATUS "${SOME_VARIABLES_THAT_DOES_NOT_EXIST}")
```
will never abort the CMake execution, and will never trigger a single warning. it will just assume `SOME_VARIABLES_THAT_DOES_NOT_EXIST` is an empty string. that's why it cannot be validated easily, I believe.
so if future CMake version adds a variable named `CMAKE_CXX_KNOWN_FEATURES`, and your CMakeLists.txt uses it, and you run old CMake release - nothing happens.

2022-02-07 17:58 UTC, closed without merging