Deprecated `names`, `filenames` and `build_modules`
conan-io/hooks pull request #369
Opened 2021-11-12 08:30 UTC by franramirez688

If `conanfile.py` recipe is using any of the legacy properties `names`, `filenames` and/or `build_modules`, this hook will show an error. It will help to avoid problems with the new `conan.tools` generators like `CMakeDeps`, `PkgConfigDeps`, etc.

Issue related: https://github.com/conan-io/conan/issues/9943
Docs: https://github.com/conan-io/conan-center-index/pull/XXXX

2021-11-12 10:20 UTC, franramirez688 commented
I think this PR is blocked till the new Conan 1.43 will be published due to the need to have this change available https://github.com/conan-io/conan/pull/10005

2021-11-12 12:10 UTC, danimtb commented
Running a tentative hook check with the changes proposed on this PR led to the following refenreces failing:

```
AIL: conan export recipes/abseil/all abseil/20210324.2@
FAIL: conan export recipes/abseil/all abseil/20210324.1@
FAIL: conan export recipes/abseil/all abseil/20210324.0@
FAIL: conan export recipes/abseil/all abseil/20200923.3@
FAIL: conan export recipes/abseil/all abseil/20200923.2@
FAIL: conan export recipes/abseil/all abseil/20200923.1@
FAIL: conan export recipes/abseil/all abseil/20200923@
FAIL: conan export recipes/abseil/all abseil/20200225.3@
FAIL: conan export recipes/abseil/all abseil/20200225.2@
FAIL: conan export recipes/abseil/all abseil/20200205@
FAIL: conan export recipes/absent/all absent/0.0.1@
FAIL: conan export recipes/absent/all absent/0.1.0@
FAIL: conan export recipes/absent/all absent/0.2.0@
FAIL: conan export recipes/absent/all absent/0.3.0@
FAIL: conan export recipes/absent/all absent/0.3.1@
FAIL: conan export recipes/acado/all acado/1.2.2-beta@
FAIL: conan export recipes/acl/all acl/2.3.1@
FAIL: conan export recipes/alembic/all alembic/1.8.3@
FAIL: conan export recipes/alembic/all alembic/1.8.2@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.1.5@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.1.6@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.1.7@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.2.1@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.3.10@
FAIL: conan export recipes/amqp-cpp/all amqp-cpp/4.3.11@
FAIL: conan export recipes/andreasbuhr-cppcoro/all andreasbuhr-cppcoro/cci.20210113@
FAIL: conan export recipes/angelscript/all angelscript/2.35.0@
FAIL: conan export recipes/any-lite/all any-lite/0.2.0@
FAIL: conan export recipes/any-lite/all any-lite/0.3.0@
FAIL: conan export recipes/any-lite/all any-lite/0.4.0@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/8.9.2@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/9.0.0@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/10.9.1@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/10.10.0@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/10.11.0@
FAIL: conan export recipes/approvaltests.cpp/all approvaltests.cpp/10.12.0@
FAIL: conan export recipes/apr/all apr/1.7.0@
FAIL: conan export recipes/apr-util/all apr-util/1.6.1@
FAIL: conan export recipes/apriltag/all apriltag/3.1.4@
FAIL: conan export recipes/apriltag/all apriltag/3.1.2@
FAIL: conan export recipes/apriltag/all apriltag/3.1.1@
FAIL: conan export recipes/arcus/all arcus/4.9.1@
FAIL: conan export recipes/arduinojson/all arduinojson/6.18.5@
FAIL: conan export recipes/arduinojson/all arduinojson/6.18.0@
FAIL: conan export recipes/arduinojson/all arduinojson/6.16.1@
FAIL: conan export recipes/arduinojson/all arduinojson/6.15.2@
FAIL: conan export recipes/argon2/all argon2/20190702@
FAIL: conan export recipes/argparse/all argparse/2.2@
FAIL: conan export recipes/argparse/all argparse/2.1@
FAIL: conan export recipes/args-parser/all args-parser/6.2.0.0@
FAIL: conan export recipes/args-parser/all args-parser/6.1.1.0@
FAIL: conan export recipes/args-parser/all args-parser/6.1.0.0@
FAIL: conan export recipes/args-parser/all args-parser/6.0.1.0@
FAIL: conan export recipes/argtable2/all argtable2/2.13@
FAIL: conan export recipes/argtable3/all argtable3/3.2.1@
FAIL: conan export recipes/argtable3/all argtable3/3.2.0@
FAIL: conan export recipes/argtable3/all argtable3/3.1.5@
FAIL: conan export recipes/armadillo/all armadillo/10.7.0@
FAIL: conan export recipes/arrow/all arrow/1.0.0@
FAIL: conan export recipes/arrow/all arrow/2.0.0@
FAIL: conan export recipes/aruco/3.x.x aruco/3.1.12@
FAIL: conan export recipes/asmjit/all asmjit/cci.20210306@
FAIL: conan export recipes/assimp/5.0.x assimp/5.0.0@
FAIL: conan export recipes/assimp/5.0.x assimp/5.0.1@
FAIL: conan export recipes/at-spi2-atk/all at-spi2-atk/2.38.0@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.38.0@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.39.1@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.40.0@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.40.1@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.40.2@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.40.3@
FAIL: conan export recipes/at-spi2-core/all at-spi2-core/2.42.0@
FAIL: conan export recipes/avahi/all avahi/0.8@
FAIL: conan export recipes/aws-c-auth/all aws-c-auth/0.6.4@
FAIL: conan export recipes/aws-c-auth/all aws-c-auth/0.6.0@
FAIL: conan export recipes/aws-c-cal/all aws-c-cal/0.5.12@
FAIL: conan export recipes/aws-c-cal/all aws-c-cal/0.5.11@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.15@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.14@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.11@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.9@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.8@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.6.7@
FAIL: conan export recipes/aws-c-common/all aws-c-common/0.4.25@
FAIL: conan export recipes/aws-c-compression/all aws-c-compression/0.2.14@
FAIL: conan export recipes/aws-c-compression/all aws-c-compression/0.2.13@
FAIL: conan export recipes/aws-c-event-stream/all aws-c-event-stream/0.2.7@
FAIL: conan export recipes/aws-c-event-stream/all aws-c-event-stream/0.1.5@
FAIL: conan export recipes/aws-c-http/all aws-c-http/0.6.7@
FAIL: conan export recipes/aws-c-http/all aws-c-http/0.6.5@
FAIL: conan export recipes/aws-c-io/all aws-c-io/0.10.9@
FAIL: conan export recipes/aws-c-io/all aws-c-io/0.10.5@
FAIL: conan export recipes/aws-c-mqtt/all aws-c-mqtt/0.7.6@
FAIL: conan export recipes/aws-c-s3/all aws-c-s3/0.1.27@
FAIL: conan export recipes/aws-c-s3/all aws-c-s3/0.1.19@
FAIL: conan export recipes/aws-checksums/all aws-checksums/0.1.12@
FAIL: conan export recipes/aws-checksums/all aws-checksums/0.1.11@
FAIL: conan export recipes/aws-checksums/all aws-checksums/0.1.5@
FAIL: conan export recipes/aws-crt-cpp/all aws-crt-cpp/0.14.3@
FAIL: conan export recipes/aws-kvs-pic/all aws-kvs-pic/cci.20210812@
FAIL: conan export recipes/aws-libfabric/all aws-libfabric/1.9.1amzncdi1.0@
FAIL: conan export recipes/aws-sdk-cpp/all aws-sdk-cpp/1.9.100@
FAIL: conan export recipes/aws-sdk-cpp/all aws-sdk-cpp/1.8.130@
FAIL: conan export recipes/backport-cpp/all backport-cpp/1.2.0@
FAIL: conan export recipes/backward-cpp/all backward-cpp/1.4@
FAIL: conan export recipes/backward-cpp/all backward-cpp/1.5@
FAIL: conan export recipes/backward-cpp/all backward-cpp/1.6@
FAIL: conan export recipes/baical-p7/all baical-p7/5.6@
FAIL: conan export recipes/bdwgc/all bdwgc/8.0.4@
FAIL: conan export recipes/bit-lite/all bit-lite/0.1.0@
FAIL: conan export recipes/bitserializer/all bitserializer/0.10@
FAIL: conan export recipes/bitserializer/all bitserializer/0.44@
FAIL: conan export recipes/bitsery/all bitsery/5.2.2@
FAIL: conan export recipes/bitsery/all bitsery/5.2.1@
FAIL: conan export recipes/bitsery/all bitsery/5.2.0@
FAIL: conan export recipes/bitsery/all bitsery/5.1.0@
FAIL: conan export recipes/boolean-lite/all boolean-lite/0.1.0@
FAIL: conan export recipes/boost/all boost/1.69.0@
FAIL: conan export recipes/boost/all boost/1.70.0@
FAIL: conan export recipes/boost/all boost/1.71.0@
FAIL: conan export recipes/boost/all boost/1.72.0@
FAIL: conan export recipes/boost/all boost/1.73.0@
FAIL: conan export recipes/boost/all boost/1.74.0@
FAIL: conan export recipes/boost/all boost/1.75.0@
FAIL: conan export recipes/boost/all boost/1.76.0@
FAIL: conan export recipes/boost/all boost/1.77.0@
FAIL: conan export recipes/box2d/2.4.x box2d/2.4.0@
FAIL: conan export recipes/box2d/2.4.x box2d/2.4.1@
FAIL: conan export recipes/breakpad/all breakpad/cci.20210521@
FAIL: conan export recipes/brigand/all brigand/cpp11-1.3.0@
FAIL: conan export recipes/brotli/all brotli/1.0.9@
FAIL: conan export recipes/brotli/all brotli/1.0.7@
FAIL: conan export recipes/bulle [...]

2021-12-30 14:59 UTC, jgsogo requested changes
ATM we cannot forbid these parameters, as they are **needed for the stable generators** to work properly.

We can print a warning and recommend the contributor to add `set_property`, but we cannot remove these ones until we deprecate `cmake_find_package[_multi]` generators (only after deprecating Conan v1).

2022-01-31 11:58 UTC, franramirez688 commented
This PR does not make sense for now. Closing it 😉

2022-01-31 11:58 UTC, closed without merging