KB-H070 Settings is mandatory
conan-io/hooks pull request #402
Opened 2022-03-08 15:37 UTC by uilianries

I would love to convert it to an error message, but doing a check, we have 89 recipes without settings on conan center index.

```python
import os
from conans.client.graph.python_requires import ConanPythonRequire
from conans.client.loader import parse_conanfile

if __name__ == "__main__":
    walk_dir = <recipes folder path>
    counter = 0
    for root, subdirs, files in os.walk(walk_dir):
        for filename in files:
            if "conanfile.py" in filename:
                try:
                    python_requires = ConanPythonRequire(None, None)
                    conanfile_path = os.path.join(root, filename)
                    _, conanfile = parse_conanfile(conanfile_path, python_requires=python_requires, generator_manager=None)
                    settings = getattr(conanfile, "settings", None)
                    if not settings:
                        print(conanfile_path)
    print(f"count: {counter}")
```

closes #371

2022-03-08 16:51 UTC, danimtb submitted a review, later dismissed

2022-03-08 16:51 UTC, danimtb commented on hooks/conan-center.py
> +            out.warn("No 'settings' detected in your conanfile.py. Add 'settings' attribute and use 'package_id(self)' to manage.")
```suggestion
            out.warn("No 'settings' detected in your conanfile.py. Add 'settings' attribute and use 'package_id(self)' method to manage the package ID.")
```

2022-03-08 16:51 UTC, danimtb commented on tests/test_hooks/conan-center/test_settings_attr.py
> +                      "Add 'settings' attribute and use 'package_id(self)' to manage.", output)
```suggestion
                      "Add 'settings' attribute and use 'package_id(self)' method to manage the package ID.", output)
```

2022-03-08 18:07 UTC, uilianries commented on tests/test_hooks/conan-center/test_settings_attr.py
> +        tools.save('conanfile.py', content=self.conanfile.replace("{}", "settings = 'os'"))
not bad idea

2022-03-09 10:20 UTC, uilianries commented on tests/test_hooks/conan-center/test_settings_attr.py
> +        tools.save('conanfile.py', content=self.conanfile.replace("{}", "settings = 'os'"))
Done.

2022-03-09 10:21 UTC, uilianries commented
Changed the rule a little, now all four values `os`, `arch`, `compiler`, `build_type` are required on `settings`, otherwise, it will rise a warning message.

2022-03-09 12:31 UTC, SSE4 approved these changes
LGTM, one more step towards 2.0

2022-03-14 20:24 UTC, jgsogo commented
I think we can turn it into an error, there are not so many recipes (report should arrive soon 😉 )

2022-03-14 20:24 UTC, jgsogo commented
I think we can turn it into an error, there are not so many recipes (report should arrive soon 😉 )

2022-03-14 21:18 UTC, uilianries commented
> I think we can turn it into an error, there are not so many recipes (report should arrive soon 😉 )

Hell yeah 😈

2022-03-15 08:43 UTC, jgsogo requested changes
Turn them to errors, only 5 references (2 recipes) are failing.

2022-03-15 09:00 UTC, uilianries commented
> Turn them to errors, only 5 references (2 recipes) are failing.

I don't know how this number was generated, but it does not follow the reality. This hook checks if `settings`attribute is declared, and `os`, `arch`, `compiler` and `build_type` are listed. Doing a quick view, there are 89 recipes without `settings`on CCI, and didn't count how many are missing settings values (header-only usually only carry `compiler` due cpp support). In case we switch it to error level, will be a disaster, probably more than 100 broken recipes.

2022-03-15 11:18 UTC, jgsogo commented
It is directly the output from the ScheculedExportCheck job

2022-03-15 11:19 UTC, jgsogo commented
🤦 ... and it is a warning so they are not failing. Shame on me!

2022-03-15 11:20 UTC, jgsogo approved these changes
Let's go with warning then

2022-03-15 12:53 UTC, merged