check for patches not referenced in conandata.yml
conan-io/hooks pull request #536
Opened 2024-04-24 07:30 UTC by ericLemanissier

reimplement part of https://github.com/ericLemanissier/conan-center-lint-patches/blob/main/lint_patches.py
results are tracked in https://github.com/conan-io/conan-center-index/issues/21146

2024-04-24 07:35 UTC, ericLemanissier commented
last PRs fixing offenders:
- https://github.com/conan-io/conan-center-index/pull/23739
- https://github.com/conan-io/conan-center-index/pull/23054
- https://github.com/conan-io/conan-center-index/pull/23155
- https://github.com/conan-io/conan-center-index/pull/23182
- https://github.com/conan-io/conan-center-index/pull/23353

2024-04-24 08:55 UTC, ericLemanissier commented
@uilianries @RubenRBS Do you have a way to test this hook on all current references in CCI ? `conan cci:export-all-versions` is not available on conan 1, and this hook is not available in conan 2 :/

2024-04-24 14:15 UTC, uilianries commented
Nice! I see it as a good improvement, but I would prefer fixing all recipes first, because it's classified as error. Otherwise, any non-related PR would be broken.

2024-04-24 14:26 UTC, ericLemanissier commented
sure, I'll do all the PRs

2024-04-24 21:11 UTC, Croydon commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
Will this actually display several errors in CCI or only the first that exit the build? Maybe convert `unused_patches` from list to string and display all at once.

Also grammar: Either `file is` if you keep it one patch file at a time or `files are` if all at once.

2024-04-24 21:32 UTC, ericLemanissier commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
you can see the actual errors generated in my message above: they are grouped with one line for each file, eg
```
[HOOK - conan-center.py] pre_export(): ERROR: [NO DANGLING PATCHES (KB-H078)] Following patch files is not referenced in conandata.yml: patches/file1.patch (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H078-NO-DANGLING-PATCHES) 
[HOOK - conan-center.py] pre_export(): ERROR: [NO DANGLING PATCHES (KB-H078)] Following patch files is not referenced in conandata.yml: patches/file2.patch (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H078-NO-DANGLING-PATCHES) 
```
Thanks for the grammar correction !

2024-04-24 22:49 UTC, Croydon commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
Yes, it works in general, my question was regarding how CCI's CI is handling such hook errors and if they abort the build on the first one or if they can display multiple errors within a single hook before it gets abort.

2024-04-25 08:21 UTC, ericLemanissier commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
AFAIU the only way hooks can interrupt the flow is by raising exceptions. the only exceptions in https://github.com/conan-io/hooks/blob/HEAD/hooks/conan-center.py are raised at the end of a "step" (pre_export, post_export etc.) when [`raise_if_error_output`](https://github.com/conan-io/hooks/blob/0d81053e4b54eac6f6cb55a6f1358e62874b7857/hooks/conan-center.py#L157) wrapper calls [`raise_if_error`](https://github.com/conan-io/hooks/blob/0d81053e4b54eac6f6cb55a6f1358e62874b7857/hooks/conan-center.py#L154), so after each check of the step has finished, and only if one of the check reported a status with a level higher than `CONAN_HOOK_ERROR_LEVEL`

2024-04-25 08:32 UTC, uilianries commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
I agree with @Croydon , keeping it in a single a output would be much simpler.

2024-04-25 08:43 UTC, ericLemanissier commented on hooks/conan-center.py
> +            out.error(f"Following patch files is not referenced in conandata.yml: patches/{patch}")
done

2024-04-25 09:01 UTC, ericLemanissier commented
As you wanted, all the patches are now grouped on the same line instead of one line per patch.
Here are two examples of logs generated:
```
[HOOK - conan-center.py] pre_export(): ERROR: [NO DANGLING PATCHES (KB-H078)] Following patch file(s) are/is not referenced in conandata.yml: patches/2.13.0-0001-fix-fallthrough.patch (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H078-NO-DANGLING-PATCHES)
```
```
[HOOK - conan-center.py] pre_export(): ERROR: [NO DANGLING PATCHES (KB-H078)] Following patch file(s) are/is not referenced in conandata.yml: patches/1.1.1.patch, patches/fix-cmake-source-dir-and-targets.patch, patches/pstring.patch, patches/strlen.patch (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H078-NO-DANGLING-PATCHES)
```
I don't think it's more readable, but as you want

2024-04-26 14:48 UTC, ericLemanissier commented
@uilianries all the fixes have been merged. The only offenders remaining are either deprecated, or not compatible with conan 2.

2024-04-26 17:25 UTC, jcar87 requested changes
Pending discussion with the team.
(likely to be merged, this is a good change, thanks @ericLemanissier )

2024-05-03 09:40 UTC, ericLemanissier commented
@jcar87 What's the opinion of the team regarding this change ?

2024-05-16 08:41 UTC, ericLemanissier commented
@jcar87 @uilianries can we please have an update on the status of this PR ?

2024-05-30 11:27 UTC, ericLemanissier commented
https://github.com/conan-io/conan-center-index/pull/24165

2024-05-30 11:27 UTC, closed without merging